// Copyright 2023 The Cockroach Authors.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0, included in the file
// licenses/APL.txt.

package bench

import (
	"fmt"
	"strings"
)

func init() {
	// Add a table with many columns and many indexes to schemas.
	var indexes strings.Builder
	for i := 0; i < 250; i++ {
		indexes.WriteString(fmt.Sprintf(
			",\nINDEX idx%d (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w)",
			i,
		))
	}
	tableK := fmt.Sprintf(`CREATE TABLE k (
		id INT PRIMARY KEY,
		a INT, b INT, c INT, d INT, e INT, f INT, g INT, h INT, i INT, j INT,
		k INT, l INT, m INT, n INT, o INT, p INT, q INT, r INT, s INT, t INT,
		u INT, v INT, w INT, x INT, y INT, z INT
		%s
	)`, indexes.String())
	schemas = append(schemas, tableK)
}

// schemas contains DDL used by benchmark queries.
var schemas = []string{
	`CREATE TABLE kv (k BIGINT NOT NULL PRIMARY KEY, v BYTES NOT NULL)`,
	`
	CREATE TABLE customer
	(
		c_id           integer        not null,
		c_d_id         integer        not null,
		c_w_id         integer        not null,
		c_first        varchar(16),
		c_middle       char(2),
		c_last         varchar(16),
		c_street_1     varchar(20),
		c_street_2     varchar(20),
		c_city         varchar(20),
		c_state        char(2),
		c_zip          char(9),
		c_phone        char(16),
		c_since        timestamp,
		c_credit       char(2),
		c_credit_lim   decimal(12,2),
		c_discount     decimal(4,4),
		c_balance      decimal(12,2),
		c_ytd_payment  decimal(12,2),
		c_payment_cnt  integer,
		c_delivery_cnt integer,
		c_data         varchar(500),
		primary key (c_w_id, c_d_id, c_id),
		index customer_idx (c_w_id, c_d_id, c_last, c_first)
	)
	`,
	`
	CREATE TABLE new_order
	(
		no_o_id  integer   not null,
		no_d_id  integer   not null,
		no_w_id  integer   not null,
		primary key (no_w_id, no_d_id, no_o_id DESC)
	)
	`,
	`
	CREATE TABLE stock
	(
		s_i_id       integer       not null,
		s_w_id       integer       not null,
		s_quantity   integer,
		s_dist_01    char(24),
		s_dist_02    char(24),
		s_dist_03    char(24),
		s_dist_04    char(24),
		s_dist_05    char(24),
		s_dist_06    char(24),
		s_dist_07    char(24),
		s_dist_08    char(24),
		s_dist_09    char(24),
		s_dist_10    char(24),
		s_ytd        integer,
		s_order_cnt  integer,
		s_remote_cnt integer,
		s_data       varchar(50),
		primary key (s_w_id, s_i_id)
	)
	`,
	`
	CREATE TABLE order_line
	(
		ol_o_id         integer   not null,
		ol_d_id         integer   not null,
		ol_w_id         integer   not null,
		ol_number       integer   not null,
		ol_i_id         integer   not null,
		ol_supply_w_id  integer,
		ol_delivery_d   timestamp,
		ol_quantity     integer,
		ol_amount       decimal(6,2),
		ol_dist_info    char(24),
		primary key (ol_w_id, ol_d_id, ol_o_id DESC, ol_number),
		index order_line_fk (ol_supply_w_id, ol_i_id),
		foreign key (ol_supply_w_id, ol_i_id) references stock (s_w_id, s_i_id)
	)
	`,
	`
	CREATE TABLE j
	(
		a INT PRIMARY KEY,
		b INT,
		INDEX b_idx (b)
	)
	`,
	`
	CREATE TABLE single_col_histogram (k TEXT PRIMARY KEY)
	`,
	`
	ALTER TABLE single_col_histogram INJECT STATISTICS '[
		{
			"columns": ["k"],
			"created_at": "2018-01-01 1:00:00.00000+00:00",
			"row_count": 30000,
			"distinct_count": 1100,
			"null_count": 0,
			"avg_size": 2,
			"histo_col_type": "STRING",
			"histo_buckets": [
				{"num_eq": 0, "num_range": 0, "distinct_range": 0, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________0"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________100"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________200"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________300"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________400"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________500"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________600"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________700"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________800"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________900"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________1000"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________1200"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________1300"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________1400"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________1500"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________1600"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________1700"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________1800"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________1900"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________2000"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________2100"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________2200"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________2300"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________2400"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________2500"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________2600"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________2700"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________2800"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________2900"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________3000"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________3100"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________3200"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________3300"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________3400"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________3500"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________3500"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________3600"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________3700"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________3800"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________3900"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________4000"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________4100"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________4200"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________4300"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________4400"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________4500"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________4600"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________4700"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________4800"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________4900"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________5100"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________5200"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________5300"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________5400"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________5500"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________5600"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________5700"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________5800"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________5900"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________6000"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________6000"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________6100"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________6200"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________6300"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________6400"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________6500"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________6600"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________6700"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________6800"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________6900"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________7000"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________7100"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________7200"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________7300"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________7400"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________7500"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________7600"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________7700"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________7800"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________7900"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________8000"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________8100"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________8200"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________8300"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________8400"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________8500"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________8600"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________8700"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________8800"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________8900"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________9000"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________9100"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________9200"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________9300"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________9400"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________9500"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________9600"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________9700"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________9800"},
				{"num_eq": 10, "num_range": 10, "distinct_range": 10, "upper_bound": "abcdefghijklmnopqrstuvwxyz___________________9900"}
			]
		}
	]'
	`,
}

// slowSchemas contains DDL statements used for BenchmarkSlowQueries.
var slowSchemas = []string{
	`
    CREATE TABLE tab1 (
        col1 INT8 NOT NULL,
        col2 INT8 NOT NULL,
        col3 INT8 NOT NULL,
        col4 INT8 NULL,
        col5 INT8 NULL,
        col6 INT8 NOT NULL,
        col7 INT8 NOT NULL,
        col8 INT8 NOT NULL,
        col9 INT8 NOT NULL,
        col10 INT8 NOT NULL,
        col11 INT8 NULL,
        col12 INT8 NULL,
        col13 INT8 NULL,
        col14 INT8 NULL,
        col15 INT8 NULL,
        col16 INT8 NOT NULL,
        col17 INT8 NOT NULL,
        col18 INT8 NULL,
        col19 INT8 NOT NULL,
        col20 INT8 NOT NULL,
        col21 INT8 NOT NULL,
        col22 INT8 NULL,
        col23 INT8 NULL,
        col24 INT8 NOT NULL,
        col25 INT8 NOT NULL,
        col26 INT8 NULL,
        col27 INT8 NULL,
        col28 INT8 NOT NULL,
        col29 INT8 NULL,
        col30 INT8 NOT NULL,
        col31 INT8 NOT NULL,
        col32 INT8 NULL,
        col33 INT8 NULL,
        col34 INT8 NULL,
        col35 INT8 NULL,
        col36 INT8 NULL,
        col37 INT8 NOT NULL,
        col38 INT8 NULL,
        col39 INT8 NULL,
        col40 INT8 NOT NULL,
        col41 INT8 NULL,
        col42 INT8 NULL,
        col43 INT8 NULL,
        col44 INT8 NULL,
        col45 INT8 NULL,
        col46 INT8 NULL,
        col47 INT8 NULL,
        col48 INT8 NULL,
        col49 INT8 NULL,
        col50 INT8 NULL,
        col51 INT8 NULL,
        col52 INT8 NULL,
        col53 INT8 NULL,
        col54 INT8 NULL,
        col55 INT8 NULL,
        col56 INT8 NULL,
        col57 INT8 NULL,
        col58 INT8 NULL,
        col59 INT8 NOT NULL,
        col60 INT8 NOT NULL,
        col61 INT8 NULL,
        col62 INT8 NOT NULL,
        col63 INT8 NULL,
        col64 INT8 NULL,
        col65 INT8 NULL,
        col66 INT8 NULL,
        col67 INT8 NOT NULL,
        col68 INT8 NULL,
        col69 INT8 NULL,
        col70 INT8 NULL,
        col71 INT8 NULL,
        col72 INT8 NULL,
        col73 INT8 NULL,
        col74 INT8 NULL,
        col75 INT8 NULL,
        col76 INT8 NULL,
        col77 INT8 NULL,
        col78 INT8 NULL,
        col79 INT8 NULL,
        col80 INT8 NULL,
        col81 INT8 NULL,
        col82 INT8 NULL,
        col83 INT8 NULL,
        col84 INT8 NULL,
        col85 INT8 NOT NULL,
        col86 INT8 NULL,
        col87 INT8 NULL,
        col88 INT8 NULL,
        col89 INT8 NULL,
        col90 INT8 NULL,
        col91 INT8 NULL,
        col92 INT8 NULL,
        col93 INT8 NULL,
        col94 INT8 NULL,
        col95 INT8 NULL,
        col96 INT8 NULL,
        col97 INT8 NULL,
        col98 INT8 NULL,
        col99 INT8 NULL,
        col100 INT8 NULL,
        col101 INT8 NULL,
        col102 INT8 NULL,
        col103 INT8 NULL,
        col104 INT8 NULL,
        col105 INT8 NULL,
        col106 INT8 NULL,
        col107 INT8 NULL,
        col108 INT8 NULL,
        col109 INT8 NULL,
        col110 INT8 NULL,
        col111 INT8 NULL,
        col112 INT8 NOT NULL,
        col113 INT8 NOT NULL,
        col114 INT8 NULL,
        col115 INT8 NULL,
        col116 INT8 NULL,
        col117 INT8 NULL,
        col118 INT8 NULL,
        col119 INT8 NOT NULL,
        col120 INT8 NOT NULL,
        col121 INT8 NULL,
        col122 INT8 NULL,
        col123 INT8 NULL,
        col124 INT8 NULL,
        col125 INT8 NULL,
        col126 INT8 NULL,
        col127 INT8 NULL,
        col128 INT8 NULL,
        col129 INT8 NULL,
        col130 INT8 NULL,
        col131 INT8 NULL,
        col132 INT8 NULL,
        col133 INT8 NULL,
        col134 INT8 NULL,
        col135 INT8 NULL,
        col136 INT8 NOT NULL,
        col137 INT8 NOT NULL,
        col138 INT8 NULL,
        col139 INT8 NULL,
        col140 INT8 NULL,
        col141 INT8 NULL,
        col142 INT8 NULL,
        col143 INT8 NULL,
        col144 INT8 NULL,
        col145 INT8 NULL,
        col146 INT8 NULL,
        col147 INT8 NULL,
        col148 INT8 NULL,
        col149 INT8 NULL,
        col150 INT8 NULL,
        CONSTRAINT "primary" PRIMARY KEY (col2 ASC, col1 ASC),
        INDEX index1 (col2 ASC, col20 ASC, col40 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index2 (col2 ASC, col18 ASC, col6 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index3 (col2 ASC, col87 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index4 (col2 ASC, col8 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index5 (col2 ASC, col4 ASC, col7 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index6 (col2 ASC, col20 ASC, col40 ASC, col30 ASC, col8 DESC) STORING (col18) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index7 (col2 ASC, col30 ASC, col8 ASC, col1 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index8 (col2 ASC, col56 ASC, col1 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index9 (col2 ASC, col8 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index10 (col2 ASC, col20 ASC, col40 ASC, col1 ASC, col8 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        CONSTRAINT check1 CHECK (col2 IN (1:::INT8, 2:::INT8, 3:::INT8, 4:::INT8, 5:::INT8, 6:::INT8, 7:::INT8, 8:::INT8, 9:::INT8, 10:::INT8, 11:::INT8, 12:::INT8, 13:::INT8, 14:::INT8, 15:::INT8, 16:::INT8, 17:::INT8, 18:::INT8, 19:::INT8, 20:::INT8, 21:::INT8, 22:::INT8, 23:::INT8, 24:::INT8))
    ) PARTITION BY LIST (col2) (
        PARTITION p1 VALUES IN ((1)),
        PARTITION p2 VALUES IN ((2)),
        PARTITION p3 VALUES IN ((3)),
        PARTITION p4 VALUES IN ((4)),
        PARTITION p5 VALUES IN ((5)),
        PARTITION p6 VALUES IN ((6)),
        PARTITION p7 VALUES IN ((7)),
        PARTITION p8 VALUES IN ((8)),
        PARTITION p9 VALUES IN ((9)),
        PARTITION p10 VALUES IN ((10)),
        PARTITION p11 VALUES IN ((11)),
        PARTITION p12 VALUES IN ((12)),
        PARTITION p13 VALUES IN ((13)),
        PARTITION p14 VALUES IN ((14)),
        PARTITION p15 VALUES IN ((15)),
        PARTITION p16 VALUES IN ((16)),
        PARTITION p17 VALUES IN ((17)),
        PARTITION p18 VALUES IN ((18)),
        PARTITION p19 VALUES IN ((19)),
        PARTITION p20 VALUES IN ((20)),
        PARTITION p21 VALUES IN ((21)),
        PARTITION p22 VALUES IN ((22)),
        PARTITION p23 VALUES IN ((23)),
        PARTITION p24 VALUES IN ((24))
    )
  `,
	`
    CREATE TABLE tab2 (
        col1 INT8 NOT NULL,
        col2 INT8 NOT NULL,
        col3 INT8 NOT NULL,
        col4 INT8 NOT NULL,
        col5 INT8 NOT NULL,
        col6 INT8 NULL,
        col7 INT8 NULL,
        col8 INT8 NOT NULL,
        col9 INT8 NULL,
        col10 INT8 NULL,
        col11 INT8 NOT NULL,
        col12 INT8 NOT NULL,
        col13 INT8 NULL,
        col14 INT8 NOT NULL,
        col15 INT8 NOT NULL,
        col16 INT8 NULL,
        col17 INT8 NULL,
        col18 INT8 NULL,
        col19 INT8 NULL,
        col20 INT8 NULL,
        col21 INT8 NULL,
        col22 INT8 NULL,
        col23 INT8 NULL,
        col24 INT8 NULL,
        col25 INT8 NULL,
        col26 INT8 NULL,
        col27 INT8 NULL,
        col28 INT8 NULL,
        col29 INT8 NOT NULL,
        col30 INT8 NULL,
        col31 INT8 NOT NULL,
        col32 INT8 NULL,
        col33 INT8 NOT NULL,
        col34 INT8 NULL,
        col35 INT8 NULL,
        col36 INT8 NULL,
        col37 INT8 NOT NULL,
        col38 INT8 NULL,
        col39 INT8 NULL,
        col40 INT8 NULL,
        col41 INT8 NULL,
        col42 INT8 NULL,
        col43 INT8 NULL,
        col44 INT8 NULL,
        col45 INT8 NULL,
        col46 INT8 NULL,
        col47 INT8 NULL,
        col48 INT8 NULL,
        col49 INT8 NULL,
        col50 INT8 NULL,
        col51 INT8 NULL,
        col52 INT8 NULL,
        col53 INT8 NULL,
        col54 INT8 NULL,
        col55 INT8 NULL,
        col56 INT8 NULL,
        col57 INT8 NULL,
        col58 INT8 NULL,
        col59 INT8 NULL,
        col60 INT8 NULL,
        col61 INT8 NULL,
        col62 INT8 NULL,
        col63 INT8 NULL,
        col64 INT8 NULL,
        col65 INT8 NULL,
        col66 INT8 NULL,
        col67 INT8 NULL,
        col68 INT8 NULL,
        col69 INT8 NULL,
        col70 INT8 NULL,
        col71 INT8 NULL,
        col72 INT8 NULL,
        col73 INT8 NULL,
        col74 INT8 NULL,
        col75 INT8 NULL,
        col76 INT8 NULL,
        col77 INT8 NULL,
        col78 INT8 NOT NULL,
        col79 INT8 NULL,
        col80 INT8 NULL,
        col81 INT8 NULL,
        col82 INT8 NULL,
        col83 INT8 NULL,
        col84 INT8 NULL,
        col85 INT8 NULL,
        col86 INT8 NULL,
        col87 INT8 NULL,
        col88 INT8 NULL,
        col89 INT8 NOT NULL,
        col90 INT8 NOT NULL,
        col91 INT8 NOT NULL,
        col92 INT8 NOT NULL,
        col93 INT8 NOT NULL,
        col94 INT8 NOT NULL,
        col95 INT8 NOT NULL,
        col96 INT8 NOT NULL,
        col97 INT8 NOT NULL,
        col98 INT8 NOT NULL,
        col99 INT8 NOT NULL,
        col100 INT8 NOT NULL,
        CONSTRAINT "primary" PRIMARY KEY (col2 ASC, col1 ASC, col1 ASC),
        CONSTRAINT fk1 FOREIGN KEY (col2, col1) REFERENCES tab1(col2, col1),
        UNIQUE INDEX index1 (col2 ASC, col1 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index2 (col2 ASC, col1 ASC, col38 ASC, col33 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index3 (col2 ASC, col11 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index4 (col2 ASC, col17 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index5 (col2 ASC, col18 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index6 (col2 ASC, col1 ASC) STORING (col38, col9, col10, col42, col40) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index7 (col2 ASC, col11 ASC, col17 ASC, col38 ASC, col8 ASC) STORING (col3, col35) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index8 (col2 ASC, col51 ASC, col17 ASC, col33 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index9 (col2 ASC, col1 ASC, col33 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        INDEX index10 (col2 ASC, col18 ASC, col1 ASC, col33 ASC) PARTITION BY LIST (col2) (
            PARTITION p1 VALUES IN ((1)),
            PARTITION p2 VALUES IN ((2)),
            PARTITION p3 VALUES IN ((3)),
            PARTITION p4 VALUES IN ((4)),
            PARTITION p5 VALUES IN ((5)),
            PARTITION p6 VALUES IN ((6)),
            PARTITION p7 VALUES IN ((7)),
            PARTITION p8 VALUES IN ((8)),
            PARTITION p9 VALUES IN ((9)),
            PARTITION p10 VALUES IN ((10)),
            PARTITION p11 VALUES IN ((11)),
            PARTITION p12 VALUES IN ((12)),
            PARTITION p13 VALUES IN ((13)),
            PARTITION p14 VALUES IN ((14)),
            PARTITION p15 VALUES IN ((15)),
            PARTITION p16 VALUES IN ((16)),
            PARTITION p17 VALUES IN ((17)),
            PARTITION p18 VALUES IN ((18)),
            PARTITION p19 VALUES IN ((19)),
            PARTITION p20 VALUES IN ((20)),
            PARTITION p21 VALUES IN ((21)),
            PARTITION p22 VALUES IN ((22)),
            PARTITION p23 VALUES IN ((23)),
            PARTITION p24 VALUES IN ((24))
        ),
        CONSTRAINT check1 CHECK (col2 IN (1:::INT8, 2:::INT8, 3:::INT8, 4:::INT8, 5:::INT8, 6:::INT8, 7:::INT8, 8:::INT8, 9:::INT8, 10:::INT8, 11:::INT8, 12:::INT8, 13:::INT8, 14:::INT8, 15:::INT8, 16:::INT8, 17:::INT8, 18:::INT8, 19:::INT8, 20:::INT8, 21:::INT8, 22:::INT8, 23:::INT8, 24:::INT8))
    ) PARTITION BY LIST (col2) (
        PARTITION p1 VALUES IN ((1)),
        PARTITION p2 VALUES IN ((2)),
        PARTITION p3 VALUES IN ((3)),
        PARTITION p4 VALUES IN ((4)),
        PARTITION p5 VALUES IN ((5)),
        PARTITION p6 VALUES IN ((6)),
        PARTITION p7 VALUES IN ((7)),
        PARTITION p8 VALUES IN ((8)),
        PARTITION p9 VALUES IN ((9)),
        PARTITION p10 VALUES IN ((10)),
        PARTITION p11 VALUES IN ((11)),
        PARTITION p12 VALUES IN ((12)),
        PARTITION p13 VALUES IN ((13)),
        PARTITION p14 VALUES IN ((14)),
        PARTITION p15 VALUES IN ((15)),
        PARTITION p16 VALUES IN ((16)),
        PARTITION p17 VALUES IN ((17)),
        PARTITION p18 VALUES IN ((18)),
        PARTITION p19 VALUES IN ((19)),
        PARTITION p20 VALUES IN ((20)),
        PARTITION p21 VALUES IN ((21)),
        PARTITION p22 VALUES IN ((22)),
        PARTITION p23 VALUES IN ((23)),
        PARTITION p24 VALUES IN ((24))
    )
  `,
	`
		CREATE TABLE table64793_1 (
			col1_0 CHAR NOT NULL, col1_1 BOOL NOT NULL, col1_2 REGPROC NOT NULL,
			col1_3 REGPROCEDURE NOT NULL, col1_4 TIMETZ NOT NULL, col1_5 FLOAT8 NULL,
			col1_6 INT2 NOT NULL, col1_7 BOOL, col1_8 BOX2D NOT NULL,
			col1_9 REGNAMESPACE NOT NULL,
			PRIMARY KEY (
				col1_8 DESC, col1_9 DESC, col1_4 DESC, col1_1, col1_2 ASC, col1_3 DESC,
				col1_0 DESC, col1_6
			),
			col1_10 INT2 NOT NULL AS (col1_6 + 22798:::INT8) VIRTUAL,
			FAMILY (col1_4), FAMILY (col1_0, col1_5), FAMILY (col1_1),
			FAMILY (col1_8, col1_3, col1_9, col1_7), FAMILY (col1_2), FAMILY (col1_6))
	`,
	`
		CREATE TYPE greeting64793 AS ENUM ('hello', 'howdy', 'hi', 'good day', 'morning');
	`,
	`
		CREATE TABLE seed64793 (
			_int2 INT2,
			_int4 INT4,
			_int8 INT8,
			_float4 FLOAT4,
			_float8 FLOAT8,
			_date DATE,
			_timestamp TIMESTAMP,
			_timestamptz TIMESTAMPTZ,
			_interval INTERVAL,
			_bool BOOL,
			_decimal DECIMAL,
			_string STRING,
			_bytes BYTES,
			_uuid UUID,
			_inet INET,
			_jsonb JSONB,
			_enum greeting64793
		);
	`,
	`
		CREATE INDEX on seed64793 (_int8, _float8, _date);
	`,
	`
		CREATE INVERTED INDEX on seed64793 (_jsonb);
	`,
	`
		CREATE TABLE table64793_2 (
			col1_0 "char" NOT NULL, col1_1 OID NOT NULL, col1_2 BIT(38) NOT NULL,
			col1_3 BIT(18) NOT NULL, col1_4 BYTES NOT NULL, col1_5 INT8 NOT NULL,
			col1_6 INTERVAL NOT NULL, col1_7 BIT(33) NOT NULL, col1_8 INTERVAL NULL,
			col1_9 GEOMETRY NOT NULL, col1_10 BOOL NOT NULL, col1_11 INT2,
			PRIMARY KEY (
				col1_4 ASC, col1_7 DESC, col1_1 ASC, col1_2 ASC, col1_10 ASC, col1_5,
				col1_0 ASC, col1_3, col1_6
			),
			UNIQUE (
				col1_8 DESC, col1_11, col1_3 DESC, col1_7, col1_6 DESC, col1_4 ASC,
				col1_1 DESC
			)
		);
	`,
	`
		CREATE TABLE table64793_3 (
			col2_0 NAME NOT NULL, col2_1 TIMETZ NOT NULL,
			PRIMARY KEY (col2_0 ASC, col2_1),
			col2_2 STRING NOT NULL AS (lower(col2_0)) VIRTUAL,
			UNIQUE (col2_0 DESC, col2_2 DESC, col2_1)
			WHERE (table64793_3.col2_2 > e'\U00002603':::STRING)
			OR (table64793_3.col2_0 != '"':::STRING),
			UNIQUE (col2_1 ASC, col2_2, col2_0),
			UNIQUE (col2_0 DESC,col2_1, col2_2),
			INDEX (col2_1 DESC),
			UNIQUE (col2_2 DESC, col2_0 ASC)
			WHERE table64793_3.col2_2 = '"':::STRING
		);
	`,
	`
		CREATE TABLE table64793_4 (
			col2_0 NAME NOT NULL, col2_1 TIMETZ NOT NULL, col3_2 REGPROC NOT NULL,
			col3_3 "char", col3_4 BOX2D, col3_5 INT8 NULL, col3_6 TIMESTAMP NOT NULL,
			col3_7 FLOAT8, col3_8 INT4 NULL, col3_9 INET NULL, col3_10 UUID NOT NULL,
			col3_11 UUID NULL, col3_12 INT2 NOT NULL, col3_13 BIT(34),
			col3_14 REGPROCEDURE NULL, col3_15 FLOAT8 NULL,
			PRIMARY KEY (
				col2_0 ASC, col2_1, col3_11 DESC, col3_13, col3_6, col3_3 DESC,
				col3_15 ASC, col3_2 ASC, col3_4 ASC, col3_9 DESC, col3_12 ASC,
				col3_8 ASC, col3_5, col3_14 ASC
			),
			UNIQUE (col3_2, col3_8 ASC)
			WHERE ((((table64793_4.col3_5 < 0:::INT8)
			AND (table64793_4.col3_3 != '':::STRING))
			AND (table64793_4.col2_1 < '00:00:00+15:59:00':::TIMETZ))
			AND (table64793_4.col3_12 > 0:::INT8))
			AND (table64793_4.col3_15 <= 1.7976931348623157e+308:::FLOAT8),
			UNIQUE (col3_10 DESC, col3_3 ASC, col2_1 DESC, col3_9 ASC)
		);
	`,
	`
		CREATE TABLE multi_col_pk (
			region STRING NOT NULL,
			id INT NOT NULL,
			c1 INT NOT NULL, c2 INT NOT NULL, c3 INT NOT NULL, c4 INT NOT NULL, c5 INT NOT NULL,
			c6 INT NOT NULL, c7 INT NOT NULL, c8 INT NOT NULL, c9 INT NOT NULL, c10 INT NOT NULL,
			c11 INT NOT NULL, c12 INT NOT NULL, c13 INT NOT NULL, c14 INT NOT NULL, c15 INT NOT NULL,
			c16 INT NOT NULL, c17 INT NOT NULL, c18 INT NOT NULL, c19 INT NOT NULL, c20 INT NOT NULL,
			c21 INT NOT NULL, c22 INT NOT NULL, c23 INT NOT NULL, c24 INT NOT NULL, c25 INT NOT NULL,
			c26 INT NOT NULL, c27 INT NOT NULL, c28 INT NOT NULL, c29 INT NOT NULL, c30 INT NOT NULL,
			c31 INT NOT NULL, c32 INT NOT NULL, c33 INT NOT NULL, c34 INT NOT NULL, c35 INT NOT NULL,
			c36 INT NOT NULL, c37 INT NOT NULL, c38 INT NOT NULL, c39 INT NOT NULL, c40 INT NOT NULL,
			c41 INT NOT NULL, c42 INT NOT NULL, c43 INT NOT NULL, c44 INT NOT NULL, c45 INT NOT NULL,
			c46 INT NOT NULL, c47 INT NOT NULL, c48 INT NOT NULL, c49 INT NOT NULL, c50 INT NOT NULL,
			CHECK (c41 IN (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200)),
			CHECK (c42 IN (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200)),
			CHECK (c43 IN (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200)),
			CHECK (c44 IN (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200)),
			CHECK (c45 IN (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200)),
			CHECK (c46 IN (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200)),
			CHECK (c47 IN (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200)),
			CHECK (c48 IN (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200)),
			CHECK (c49 IN (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200)),
			CHECK (c50 IN (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200)),
			CHECK (region IN ('east', 'west', 'north', 'south')),
			INDEX (c41, c31),
			INDEX (c42, c32),
			INDEX (c43, c33),
			INDEX (c44, c34),
			INDEX (c45, c35),
			INDEX (c46, c36),
			INDEX (c47, c37),
			INDEX (c48, c38),
			INDEX (c49, c39),
			INDEX (c50, c40),
			PRIMARY KEY (region, id)
		);
	`,
	`
		CREATE TABLE multi_col_pk_no_indexes (
			region STRING NOT NULL,
			id INT NOT NULL,
			c1 INT NOT NULL, c2 INT NOT NULL, c3 INT NOT NULL, c4 INT NOT NULL, c5 INT NOT NULL,
			c6 INT NOT NULL, c7 INT NOT NULL, c8 INT NOT NULL, c9 INT NOT NULL, c10 INT NOT NULL,
			c11 INT NOT NULL, c12 INT NOT NULL, c13 INT NOT NULL, c14 INT NOT NULL, c15 INT NOT NULL,
			c16 INT NOT NULL, c17 INT NOT NULL, c18 INT NOT NULL, c19 INT NOT NULL, c20 INT NOT NULL,
			c21 INT NOT NULL, c22 INT NOT NULL, c23 INT NOT NULL, c24 INT NOT NULL, c25 INT NOT NULL,
			c26 INT NOT NULL, c27 INT NOT NULL, c28 INT NOT NULL, c29 INT NOT NULL, c30 INT NOT NULL,
			c31 INT NOT NULL, c32 INT NOT NULL, c33 INT NOT NULL, c34 INT NOT NULL, c35 INT NOT NULL,
			c36 INT NOT NULL, c37 INT NOT NULL, c38 INT NOT NULL, c39 INT NOT NULL, c40 INT NOT NULL,
			c41 INT NOT NULL, c42 INT NOT NULL, c43 INT NOT NULL, c44 INT NOT NULL, c45 INT NOT NULL,
			c46 INT NOT NULL, c47 INT NOT NULL, c48 INT NOT NULL, c49 INT NOT NULL, c50 INT NOT NULL,
			PRIMARY KEY (region, id)
		);
	`,
}
